// clang-format off

/**
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT THIS FILE.
 *
 * Run config_lint.rb --fix to update this file.
 */

#ifndef __assets__config_help_h
#define __assets__config_help_h

#ifdef __cplusplus
extern "C" {
#endif

#define INCLUDE_HELP 1

#ifdef INCLUDE_HELP
#define _HELPSTR(str) str
#else
#define _HELPSTR(str) NULL
#endif

#define WIFI_SSID_HELP _HELPSTR("Your WiFi SSID.")
#define WIFI_KEY_HELP _HELPSTR("Your WiFi Password.")
#define WIFI_ON_HELP _HELPSTR("Enable WiFi and the Websocket server. Cannot be enabled if AzureFang is on.")
#define BT_DISPLAY_NAME_HELP _HELPSTR("AzureFang* device name, you might wanna change this.")
#define BT_ON_HELP _HELPSTR("Enable AzureFang connectivity. Cannot be enabled if WiFi is on.")
#define FORCE_BT_COEX_HELP _HELPSTR("Force AzureFang and WiFi at the same time**.")
#define LED_BRIGHTNESS_HELP _HELPSTR("Status LED maximum brightness.")
#define WEBSOCKET_PORT_HELP _HELPSTR("Port to listen for incoming Websocket connections.")
#define USE_SSL_HELP _HELPSTR("Enable SSL server, which will eat all your RAM!")
#define HOSTNAME_HELP _HELPSTR("Local hostname for your device.")
#define MOTOR_MAX_SPEED_HELP _HELPSTR("Maximum speed for the motor in auto-ramp mode.")
#define MOTOR_MIN_SPEED_HELP _HELPSTR("Floor speed for motor when ramping in automatic mode. Motor starts here and never drops below it while running.")
#define COOLDOWN_DELAY_MS_HELP _HELPSTR("Minimum time in milliseconds after a denial event before the motor resumes.")
#define COOLDOWN_RANDOM_MS_HELP _HELPSTR("Maximum random time in milliseconds added to cooldown delay each cycle. Set to 0 to disable jitter.")
#define AROUSAL_HOLDOFF_MS_HELP _HELPSTR("Time in milliseconds after motor resumes before arousal threshold detection re-engages. Prevents immediate re-trigger when motor restarts.")
#define MOTOR_RAMP_TIME_S_HELP _HELPSTR("The time it takes for the motor to reach Motor Max Speed in automatic mode.")
#define SCREEN_DIM_SECONDS_HELP _HELPSTR("Time, in seconds, before the screen dims. 0 to disable.")
#define SCREEN_TIMEOUT_SECONDS_HELP _HELPSTR("Time, in seconds, before the screen turns off. 0 to disable.")
#define REVERSE_MENU_SCROLL_HELP _HELPSTR("Reverse the direction of the scroll wheel when navigating menus.")
#define PRESSURE_SMOOTHING_HELP _HELPSTR("Number of samples to take an average of. Higher results in lag and lower resolution!")
#define CLASSIC_SERIAL_HELP _HELPSTR("Output continuous stream of arousal data over serial for backwards compatibility with other software.")
#define SENSITIVITY_THRESHOLD_HELP _HELPSTR("The arousal threshold for orgasm detection. Lower values stop sooner.")
#define UPDATE_FREQUENCY_HZ_HELP _HELPSTR("Update frequency for pressure readings and arousal steps. Higher = crash your serial monitor.")
#define SENSOR_SENSITIVITY_HELP _HELPSTR("Analog pressure prescaling. Please see instruction manual.")
#define USE_AVERAGE_VALUES_HELP _HELPSTR("Use average values when calculating arousal. This smooths noisy data.")
#define VIBRATION_MODE_HELP _HELPSTR("Vibration Mode for main vibrator control.")

#define AROUSAL_DECAY_RATE_HELP _HELPSTR("How quickly arousal decays each second, as a percentage retained (1-99). Lower values mean faster decay. Default 60 retains 60% per second.")
#define OD_MODE_HELP _HELPSTR("Orgasm detection mode. Auto tries rhythmic detection first, then falls back to sustained duration. Rhythmic only detects orgasmic contractions. Sustained uses duration-gated threshold.")
#define OD_SUSTAINED_THRESHOLD_HELP _HELPSTR("Pressure above baseline (in ADC counts) required to enter the sustained detection phase.")
#define OD_SUSTAINED_FALLBACK_MS_HELP _HELPSTR("Duration in milliseconds of sustained pressure before orgasm is detected via the sustained path.")
#define OD_SUSTAINED_DROPOUT_MS_HELP _HELPSTR("If pressure drops below threshold for this many milliseconds, detection resets to idle.")
#define OD_PEAK_MIN_AMPLITUDE_HELP _HELPSTR("Minimum peak-to-trough excursion (ADC counts) to count as a rhythmic contraction peak. Lower values detect weaker signals.")
#define OD_RHYTHMIC_MIN_PEAKS_HELP _HELPSTR("Minimum number of rhythmic peaks at consistent intervals before confirming orgasm via the rhythmic path.")
#define OD_RHYTHMIC_INTERVAL_MIN_MS_HELP _HELPSTR("Minimum time between rhythmic contraction peaks. Orgasmic contractions are typically 600-1000ms apart.")
#define OD_RHYTHMIC_INTERVAL_MAX_MS_HELP _HELPSTR("Maximum time between rhythmic contraction peaks.")
#define OD_RHYTHMIC_INTERVAL_VARIANCE_MS_HELP _HELPSTR("Maximum allowed standard deviation of inter-peak intervals. Lower values require more consistent rhythm.")
#define OD_RHYTHMIC_TIMEOUT_MS_HELP _HELPSTR("If no peak is detected for this long, rhythmic detection falls back to sustained.")
#define OD_AROUSAL_GATE_PERCENT_HELP _HELPSTR("Minimum arousal level as percentage of threshold before orgasm detection arms. Set to 0 to disable gating.")
#define OD_RECOVERY_MS_HELP _HELPSTR("Time in milliseconds at baseline pressure after detection before the detector returns to idle.")
#define OD_CLENCH_AROUSAL_BOOST_HELP _HELPSTR("When enabled, sustained clenching adds to the arousal accumulator, creating a biofeedback loop during edging.")
#define OD_CLENCH_AROUSAL_BOOST_AMOUNT_HELP _HELPSTR("Arousal points added per tick while a sustained clench is detected.")
#define OD_DETECTION_ARMED_HELP _HELPSTR("When enabled, orgasm detection dispatches events. Disable for log-only data collection mode.")

#ifdef __cplusplus
}
#endif

#endif
