name: Build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    env:
      BUNDLE_PATH: ~/.cache/bundle

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: "0"
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Bundle Install
      run: |
        sudo gem install bundler
        bundle install
      working-directory: ./bin

    - name: Run Static Analysis
      run: |
        bundle exec ruby config_lint.rb
      working-directory: ./bin

    - name: Run PlatformIO
      run: pio run
      
    - name: Rename Firmware
      run: cp .pio/build/esp32dev/firmware.bin update.bin
      
    - name: Upload Firmware
      uses: actions/upload-artifact@v2
      with:
        path: update.bin
        if-no-files-found: error
